version: "3.0"

services:
  frontapp:
    build: ./FrontEnd
    image: junyongcho/frontapp:latest
    ports:
      - "80:80"

  backapp:
    build: ./BackEnd
    image: ${DOCKER_USR}/backapp:latest
    ports:
      - "5000:5000"